import React, { useEffect, useState } from 'react';
import { getNotes, CATEGORIES } from '../api.js';
import { useSearchParams } from 'react-router-dom';
import NoteCard from '../components/NoteCard.jsx';

export default function Notes() {
  const [searchParams] = useSearchParams();
  const [notes, setNotes] = useState([]); const [query, setQuery] = useState(searchParams.get('q') || ''); const [category, setCategory] = useState(searchParams.get('category') || ''); const [sort, setSort] = useState('views_desc'); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { const t = setTimeout(() => { setLoading(true); getNotes({ search: query, category, sort }).then(setNotes).catch(e => setError(e.message)).finally(() => setLoading(false)); }, 250); return () => clearTimeout(t); }, [query, category, sort]);
  return <><header className="page-hero text-center"><div className="container"><h1 className="fw-bold">Browse Notes</h1><p className="mb-0">Find study material shared by the community</p></div></header><div className="container py-5"><div className="category-card mb-4"><div className="row g-3 align-items-center"><div className="col-md-5"><div className="input-group"><span className="input-group-text bg-white border-end-0"><i className="fa-solid fa-magnifying-glass"></i></span><input type="search" className="form-control border-start-0" placeholder="Search title, description or author..." value={query} onChange={e => setQuery(e.target.value)} /></div></div><div className="col-md-3"><select className="form-select" value={category} onChange={e => setCategory(e.target.value)}><option value="">All Categories</option>{CATEGORIES.map(c => <option value={c.id} key={c.id}>{c.name}</option>)}</select></div><div className="col-md-3"><select className="form-select" value={sort} onChange={e => setSort(e.target.value)}><option value="views_desc">Most Viewed</option><option value="newest">Newest</option><option value="title_asc">Title (A-Z)</option></select></div><div className="col-md-1 text-md-end"><span className="badge-cat">{notes.length}</span></div></div></div>{error && <div className="alert alert-danger">Could not load notes: {error}</div>}<div className="row g-4">{loading ? <p className="text-muted">Loading notes...</p> : notes.length ? notes.map(n => <NoteCard note={n} key={n._id} />) : <div className="col-12"><div className="empty-state"><i className="fa-regular fa-folder-open"></i><p>No notes match your search.</p></div></div>}</div></div></>;
}
